##***기수정렬(radix_sort)***

In [2]:
from queue import Queue # python queue 모듈의 queue 사용
def radix_sort(A): 
    queues = [] # 큐의 리스트
    for i in range(BUCKETS):
        queues.append(Queue()) # 버킷 큐 사용
        
    n = len (A)
    factor = 1 # 1의 자리부터 시작
    for d in range(DIGITS): # 모든 자리에 대해
        for i in range(n): # 자릿수에 따라 큐 삽입
            queues[(A[i]//factor) % 10].put(A[i]) # 숫자를 삽입
        j = 0
        for b in range(BUCKETS): # 버킷에서 꺼내어 원래 리스트로
            while not queues[b].empty(): # b번째 큐가 공백이 아닌 
                A[j] = queues[b].get() # 원소를 꺼내 리스트에 저장
                j += 1
        factor *= 10
        print("STEP", d + 1, A)
        
import random
BUCKETS = 10
DIGITS = 4
data = []
for i in range(10):
    data.append(random.randint(1, 9999))
radix_sort(data)
print("Radix:", data)

STEP 1 [5090, 1470, 9151, 4722, 4733, 2625, 6056, 1317, 1028, 3459]
STEP 2 [1317, 4722, 2625, 1028, 4733, 9151, 6056, 3459, 1470, 5090]
STEP 3 [1028, 6056, 5090, 9151, 1317, 3459, 1470, 2625, 4722, 4733]
STEP 4 [1028, 1317, 1470, 2625, 3459, 4722, 4733, 5090, 6056, 9151]
Radix: [1028, 1317, 1470, 2625, 3459, 4722, 4733, 5090, 6056, 9151]

##***계수정렬(counting_sort)***

In [3]:
def counting_sort(A):
    output = [0] * len(A)
    count = [0] * MAX_VAL
    
    for i in A:
        count[i] += 1
        
    for i in range(MAX_VAL):
        count[i] += count[i - 1]
    
    for i in range(len(A)):
        output[count[A[i]] - 1] = A[i]
        count[A[i]] -= 1
        
    for i in range(len(A)):
        A[i] = output[i]
        
MAX_VAL = 10
data = [1, 4, 6, 1, 4 ,3 , 7, 3, 2]
print("ORIGINAL : ", data)
counting_sort(data)
print("COUNTING : ", data)

ORIGINAL :  [1, 4, 6, 1, 4, 3, 7, 3, 2]
COUNTING :  [1, 1, 2, 3, 3, 4, 4, 6, 7]

##***horspool algorithm***

In [13]:
NO_OF_CHARS = 128
def shift_table(pat):
    m = len(pat)
    tbl = [m]*NO_OF_CHARS
    
    for i in range(m - 1):
        tbl[ord(pat[i])] = m - 1 - i
        
    return tbl

def search_horspool(T, P):
    m = len(P)
    n = len(T)
    t = shift_table(P)
    print(t)
    i = m - 1
    while(i <= n - 1):
        k = 0
        while k <= m - 1 and P[m - 1 - k] == T[i - k]:
            k += 1
        if k == m:
            return i - m + 1
        else:
            #print(T[i])
            #print(t[ord(T[i])])
            i += t[ord(T[i])]
            #print(i)
    return -1 

print("패턴의 위치 : ", search_horspool("APPLEMANGOBANANAGRAPE", "BANANA"))

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
패턴의 위치 :  10

In [ ]:
M = 13
table = [None]*M
def hashFn(key):
    return key & M

def lp_insert(key):
    id = hashFn(key)
    count = M
    while count > 0 and (table[id] != None and table[id] != -1):
        id = (id + 1 + M) % M
        count -= 1
    if count > 0:
        table[id] = key
    return

def lp_search(key):
    id = hashFn(key)
    count = M
    while count > 0 :
        if table[id] == None :
            return None
        if table[id] != -1 and table[id] == key:
            return table[id]
        id = (id + 1 + M) % M
        count -= 1
    return None

def lp_delete(key):
    id = hashFn(key)
    count = M
    while count > 0:
        if table[id] == None : return
        if table[id] != -1 and table[id] == key:
            table[id] = -1
            return
        id = (id + 1 + M) % M
        count -= 1
        
print(" 최초: ", table)
lp_insert(45); print("45 삽입", table)
pritn("46 탐색:", lp_search(46))